server:
  tomcat:
    uri-encoding: UTF-8
    connection-timeout: 5000ms
    min-spare-threads: 30
    max-threads: 200
  port: 8080
  servlet:
    context-path: /mywork

spring:
  devtools: #热部署
    livereload:
      enabled: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_work?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Mzy001007

  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: zhiyuem1@163.com
    password: Mzy001007

  data:
    mongodb:
      host: localhost
      port: 27017
      database: my_work
      authentication-database: admin
      username: root
      password: Mzy001007

mybatis-plus:
  mapper-locations: classpath:dao/*.xml
  type-aliases-package: com.markmzy.mywork.wx.model
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true

mywork:
  jwt:
    #密钥
    secret: Mzy001007
    #令牌过期时间 (天)
    expire: 5
    #令牌缓存时间 (天)
    cache-expire: 10

  face:
    createFaceModelUrl: http://192.168.0.101:3000/create_face_model
    checkinUrl: http://192.168.0.101:3000/checkin

  email:
    system: zhiyuem1@163.com
    hr: 199703209@qq.com

  image-folder: Users/Markmzy/Desktop/image

  #调用Python人脸模型 需要定期更新
  code: BBAFD1C12ACCD00E

wx:
  app-id: wx95d20548577d0986
  app-secret: 2601953310d4736d04d2ccd06b0ec83a
  app-superCode: 19970320